using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;
using AdonisUI.Controls;
using CUE4Parse.FileProvider.Objects;
using FModel.Services;
using FModel.Settings;
using FModel.ViewModels;
using FModel.Views.Resources.Controls;
using Microsoft.Win32;

namespace FModel.Views;

/// <summary>
/// Interaction logic for TableViewerWindow.xaml
/// Shows data tables and curve tables as a spreadsheet, the way the editor does.
/// Rows are held as plain string arrays and only ever referenced, so tables with
/// hundreds of thousands of rows stay openable: filtering and sorting never copy cell data.
/// </summary>
public partial class TableViewerWindow : AdonisWindow
{
    /// <summary>Above this many selected cells copying is refused, the clipboard cannot take it anyway.</summary>
    private const int _MAX_COPIED_CELLS = 5000;

    private readonly List<TableDocument> _documents;
    private readonly string _assetName;
    private readonly DispatcherTimer _filterDebounce;

    private TableDocument _current;
    private IReadOnlyList<TableRow> _rows = [];
    private CancellationTokenSource _filterCancellation;
    private bool _isExporting;

    public TableViewerWindow(IReadOnlyList<TableDocument> documents, string assetName)
    {
        _documents = documents?.ToList() ?? [];
        _assetName = assetName;

        InitializeComponent();

        _filterDebounce = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(250) };
        _filterDebounce.Tick += async (_, _) =>
        {
            _filterDebounce.Stop();
            await ApplyFilterAsync();
        };

        Title = $"{TryFindResource("UI_TableViewer") as string ?? "Table Viewer"} - {assetName}";
        TableSelector.ItemsSource = _documents;
        TableSelector.Visibility = _documents.Count > 1 ? Visibility.Visible : Visibility.Collapsed;
        if (_documents.Count > 0) TableSelector.SelectedIndex = 0;
        else SetStatus(TryFindResource("UI_TableViewer_Empty") as string);
    }

    /// <summary>
    /// Loads every data/curve table of <paramref name="entry"/>. Returns null when the asset holds none.
    /// Call off the UI thread, the window itself must then be created on it.
    /// </summary>
    public static IReadOnlyList<TableDocument> Load(GameFile entry, Action<string> progress = null, CancellationToken cancellationToken = default)
    {
        var provider = ApplicationService.ApplicationView.CUE4Parse.Provider;
        var package = provider.LoadPackage(entry);
        var documents = TableDocumentBuilder.Build(package.GetExports(), progress, cancellationToken);
        return documents.Count > 0 ? documents : null;
    }

    private async void OnTableSelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        _current = TableSelector.SelectedItem as TableDocument;
        BuildColumns();
        await ApplyFilterAsync();

        var isCurve = _current?.Kind == ETableKind.Curve;
        CurveSplitter.Visibility = isCurve ? Visibility.Visible : Visibility.Collapsed;
        CurvePanel.Visibility = isCurve ? Visibility.Visible : Visibility.Collapsed;
        DrawCurve(null);
    }

    /// <summary>
    /// Columns are generated by hand: cells are indexed, not named, which is what keeps a row cheap.
    /// </summary>
    private void BuildColumns()
    {
        Grid.Columns.Clear();
        if (_current == null) return;

        for (var i = 0; i < _current.Columns.Count; i++)
        {
            Grid.Columns.Add(new DataGridTextColumn
            {
                // a TextBlock header keeps the underscores of property names visible
                Header = new TextBlock { Text = _current.Columns[i] },
                Binding = new Binding($"Cells[{i}]") { Mode = BindingMode.OneTime },
                // a fixed width is what keeps a huge table fast: auto sizing makes the grid
                // measure cells outside the viewport, which defeats row virtualization
                Width = new DataGridLength(i == 0 ? 240 : 170),
                MaxWidth = 900,
                CanUserSort = true
            });
        }
    }

    private void OnFilterTextChanged(object sender, TextChangedEventArgs e)
    {
        _filterDebounce.Stop();
        _filterDebounce.Start();
    }

    /// <summary>
    /// Filtering only builds a new list of references, the cells themselves are never duplicated.
    /// It runs off the UI thread because a big table means a few million string comparisons.
    /// </summary>
    private async Task ApplyFilterAsync()
    {
        if (_current == null)
        {
            _rows = [];
            Grid.ItemsSource = null;
            return;
        }

        var filter = FilterBox.Text;
        var source = _current.Rows;

        _filterCancellation?.Cancel();
        _filterCancellation?.Dispose();
        _filterCancellation = new CancellationTokenSource();
        var cancellationToken = _filterCancellation.Token;

        IReadOnlyList<TableRow> result;
        if (string.IsNullOrWhiteSpace(filter))
        {
            result = source;
        }
        else
        {
            SetStatus(TryFindResource("UI_TableViewer_Filtering") as string);
            try
            {
                result = await Task.Run(() =>
                {
                    var matches = new List<TableRow>();
                    foreach (var row in source)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        if (row.Contains(filter)) matches.Add(row);
                    }

                    return (IReadOnlyList<TableRow>) matches;
                }, cancellationToken).ConfigureAwait(true);
            }
            catch (OperationCanceledException)
            {
                return; // a newer keystroke took over
            }
        }

        if (cancellationToken.IsCancellationRequested) return;

        foreach (var column in Grid.Columns) column.SortDirection = null;

        _rows = result;
        Grid.ItemsSource = _rows;
        UpdateStatus();
    }

    /// <summary>
    /// The grid is bound to a plain list, so sorting happens here: numeric columns sort as numbers.
    /// </summary>
    private void OnSorting(object sender, DataGridSortingEventArgs e)
    {
        var index = Grid.Columns.IndexOf(e.Column);
        if (index < 0 || _rows.Count == 0) return;

        e.Handled = true;
        var ascending = e.Column.SortDirection != ListSortDirection.Ascending;
        foreach (var column in Grid.Columns) column.SortDirection = null;
        e.Column.SortDirection = ascending ? ListSortDirection.Ascending : ListSortDirection.Descending;

        var values = new string[_rows.Count];
        for (var i = 0; i < _rows.Count; i++)
            values[i] = index < _rows[i].Cells.Length ? _rows[i].Cells[index] ?? string.Empty : string.Empty;

        // parsing once per row beats parsing inside the comparison
        var numbers = new double[values.Length];
        var numeric = true;
        for (var i = 0; i < values.Length && numeric; i++)
        {
            if (string.IsNullOrEmpty(values[i])) numbers[i] = double.MinValue;
            else if (!double.TryParse(values[i], NumberStyles.Any, CultureInfo.InvariantCulture, out numbers[i])) numeric = false;
        }

        var order = Enumerable.Range(0, _rows.Count).ToArray();
        Comparison<int> ascendingComparison = numeric
            ? (a, b) => numbers[a].CompareTo(numbers[b])
            : (a, b) => string.Compare(values[a], values[b], StringComparison.OrdinalIgnoreCase);

        Array.Sort(order, ascending ? ascendingComparison : (a, b) => ascendingComparison(b, a));

        var sorted = new List<TableRow>(_rows.Count);
        foreach (var position in order) sorted.Add(_rows[position]);

        _rows = sorted;
        Grid.ItemsSource = _rows;
    }

    private void OnRowSelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (_current?.Kind != ETableKind.Curve) return;

        DrawCurve(SelectedCurve());
    }

    private TableCurve SelectedCurve()
    {
        var name = SelectedRowName();
        return name != null && _current != null && _current.Curves.TryGetValue(name, out var curve) ? curve : null;
    }

    private string SelectedRowName()
    {
        if (Grid.SelectedCells.Count > 0 && Grid.SelectedCells[0].Item is TableRow cell)
            return cell.Name;

        return (Grid.SelectedItem as TableRow)?.Name;
    }

    private void OnCurveCanvasSizeChanged(object sender, SizeChangedEventArgs e) => DrawCurve(SelectedCurve());

    /// <summary>
    /// Plots the curve keys, scaled to the panel, with the value range written in a corner.
    /// </summary>
    private void DrawCurve(TableCurve curve)
    {
        CurveCanvas.Children.Clear();
        CurveCaption.Text = string.Empty;

        if (curve == null || curve.Keys.Count == 0 || CurveCanvas.ActualWidth <= 1 || CurveCanvas.ActualHeight <= 1)
        {
            if (_current?.Kind == ETableKind.Curve)
                CurveCaption.Text = TryFindResource("UI_TableViewer_PickCurve") as string;
            return;
        }

        const double padding = 24;
        var width = CurveCanvas.ActualWidth - padding * 2;
        var height = CurveCanvas.ActualHeight - padding * 2;

        var timeRange = Math.Abs(curve.MaxTime - curve.MinTime) < float.Epsilon ? 1 : curve.MaxTime - curve.MinTime;
        var valueRange = Math.Abs(curve.MaxValue - curve.MinValue) < float.Epsilon ? 1 : curve.MaxValue - curve.MinValue;

        var axisBrush = (Brush) FindResource(AdonisUI.Brushes.Layer3BorderBrush);
        var curveBrush = (Brush) FindResource(AdonisUI.Brushes.AccentInteractionBrush);

        CurveCanvas.Children.Add(new Line
        {
            X1 = padding, Y1 = padding + height, X2 = padding + width, Y2 = padding + height,
            Stroke = axisBrush, StrokeThickness = 1
        });
        CurveCanvas.Children.Add(new Line
        {
            X1 = padding, Y1 = padding, X2 = padding, Y2 = padding + height,
            Stroke = axisBrush, StrokeThickness = 1
        });

        var polyline = new Polyline { Stroke = curveBrush, StrokeThickness = 2 };
        var keys = curve.Keys.OrderBy(key => key.Time).ToArray();
        var showDots = keys.Length <= 500; // a curve with thousands of keys only needs its line

        foreach (var key in keys)
        {
            var x = padding + (key.Time - curve.MinTime) / timeRange * width;
            var y = padding + height - (key.Value - curve.MinValue) / valueRange * height;
            polyline.Points.Add(new Point(x, y));

            if (!showDots) continue;

            var dot = new Ellipse { Width = 5, Height = 5, Fill = curveBrush };
            Canvas.SetLeft(dot, x - 2.5);
            Canvas.SetTop(dot, y - 2.5);
            CurveCanvas.Children.Add(dot);
        }

        CurveCanvas.Children.Add(polyline);
        CurveCaption.Text = $"{curve.Name}  |  time {curve.MinTime:0.###} → {curve.MaxTime:0.###}  |  " +
                            $"value {curve.MinValue:0.###} → {curve.MaxValue:0.###}  |  {curve.Keys.Count} keys";
    }

    private void OnCopyCellClick(object sender, RoutedEventArgs e)
    {
        if (Grid.SelectedCells.Count > _MAX_COPIED_CELLS)
        {
            SetStatus($"Too many cells selected to copy ({Grid.SelectedCells.Count})");
            return;
        }

        var values = new List<string>(Grid.SelectedCells.Count);
        foreach (var cell in Grid.SelectedCells)
        {
            if (cell.Item is not TableRow row) continue;

            var index = Grid.Columns.IndexOf(cell.Column);
            if (index < 0 || index >= row.Cells.Length) continue;

            var value = row.Cells[index];
            if (!string.IsNullOrEmpty(value)) values.Add(value);
        }

        if (values.Count == 0) return;

        try
        {
            Clipboard.SetText(string.Join(Environment.NewLine, values));
        }
        catch (Exception exception)
        {
            FLogger.Append(ELog.Error, () => FLogger.Text($"Could not copy to the clipboard: {exception.Message}", Constants.WHITE, true));
        }
    }

    /// <summary>
    /// Writes what is currently displayed, streamed to disk so the row count does not matter.
    /// </summary>
    private async void OnExportCsvClick(object sender, RoutedEventArgs e)
    {
        if (_current == null || _isExporting) return;

        var directory = UserSettings.Default.PropertiesDirectory;
        if (string.IsNullOrWhiteSpace(directory)) directory = UserSettings.Default.OutputDirectory;

        var dialog = new SaveFileDialog
        {
            FileName = $"{_assetName}_{_current.Name}.csv",
            DefaultExt = ".csv",
            Filter = "CSV (*.csv)|*.csv|All files (*.*)|*.*",
            InitialDirectory = Directory.Exists(directory) ? directory : null
        };

        if (dialog.ShowDialog(this) != true) return;

        _isExporting = true;
        ExportCsvButton.IsEnabled = false;

        var path = dialog.FileName;
        var columns = _current.Columns;
        var rows = _rows;

        try
        {
            SetStatus($"Writing {rows.Count} rows...");
            await Task.Run(() =>
            {
                using var writer = new StreamWriter(path, false, System.Text.Encoding.UTF8);
                TableDocumentBuilder.WriteCsv(writer, columns, rows);
            }).ConfigureAwait(true);

            var count = rows.Count;
            FLogger.Append(ELog.Information, () =>
            {
                FLogger.Text($"Saved {count} rows to ", Constants.WHITE);
                FLogger.Link(System.IO.Path.GetFileName(path), path, true);
            });
            SetStatus($"Saved {count} rows to {path}");
        }
        catch (Exception exception)
        {
            FLogger.Append(ELog.Error, () => FLogger.Text($"Could not save the csv: {exception.Message}", Constants.WHITE, true));
            SetStatus(exception.Message);
        }
        finally
        {
            _isExporting = false;
            ExportCsvButton.IsEnabled = true;
        }
    }

    private void UpdateStatus()
    {
        if (_current == null) return;

        SetStatus($"{_rows.Count} / {_current.RowCount} rows, {_current.ColumnCount} columns" +
                  (string.IsNullOrEmpty(_current.RowStructName) ? string.Empty : $" - {_current.RowStructName}"));
    }

    private void SetStatus(string status) => Status.Text = status ?? string.Empty;
}
