name: FModel-JP- exe Builder

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: .NET 8 Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: .NET Restore
        run: dotnet restore FModel/FModel/FModel.csproj

      - name: .NET Publish
        run: dotnet publish "./FModel/FModel/FModel.csproj" -c Release --no-restore --no-self-contained -r win-x64 -f net8.0-windows -o "./FModel/FModel/bin/Publish/" -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:DebugType=None -p:GenerateDocumentationFile=false -p:DebugSymbols=false

      - name: Create ZIP File
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: ${{ github.sha }}.zip
          path: ./FModel/FModel/bin/Publish/FModel.exe

      - name: Add Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'FModel-JP- Release'
          tag: 'qa'
          artifacts: |
           ${{ github.sha }}.zip
          allowUpdates: true

      - name: Get App Version
        id: package_version
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        with:
          proj-path: ./FModel/FModel/FModel.csproj

      - name: Install Requests
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Set Secrets
        run: |
          echo '${{ secrets.SECRETS }}' > secrets.py

      - name: Update Download Url
        run: |
          python Update_DownloadUrl.py "${{ github.sha }}" "${{ steps.package_version.outputs.version }}"